"""Frame ids and shared topic names (M0). Mirrors ``nuway_common/frames.h``."""

FRAME_MAP = "map"
FRAME_ODOM = "odom"
FRAME_BASE_LINK = "base_link"
FRAME_LIDAR_TOP = "lidar_top"
FRAME_IMU = "imu"
FRAME_GNSS = "gnss"

TOPIC_CLOCK = "/clock"
TOPIC_RESET_EVENT = "/nuway/sim/reset_event"
TOPIC_TICK_TIMEOUT = "/nuway/sim/tick_timeout"
TOPIC_VEHICLE_STATE = "/nuway/sim/vehicle_state"
TOPIC_GT_EGO_ODOM = "/nuway/gt/ego_odom"
TOPIC_GT_AGENTS = "/nuway/gt/agents"
TOPIC_GT_TRAFFIC_LIGHTS = "/nuway/gt/traffic_lights"
TOPIC_LANE_GRAPH = "/nuway/map/lane_graph"
TOPIC_ROUTE_PLAN = "/nuway/route/plan"
TOPIC_REFERENCE_LINE = "/nuway/route/reference_line"
TOPIC_ROUTE_WAYPOINTS = "/nuway/route/waypoints"
TOPIC_POSE = "/nuway/loc/pose"
TOPIC_PERCEPTION_AGENTS = "/nuway/perception/agents"
TOPIC_PERCEPTION_OCCUPANCY = "/nuway/perception/occupancy"
TOPIC_PERCEPTION_TRAFFIC_LIGHTS = "/nuway/perception/traffic_lights"
TOPIC_CONTROL_COMMAND = "/nuway/control/command"
TOPIC_CONTROL_DEBUG = "/nuway/control/debug"
TOPIC_DIAG_PREFIX = "/nuway/diag/"
TOPIC_CAMERA_INFO_FMT = "/nuway/sensors/{cam}/camera_info"
